# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suoLNk0BNQWJ4KUsQl4rWIw4Kud2IVA6
"""

# Importing Necessary Libraries
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans, DBSCAN, MeanShift, AgglomerativeClustering
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.metrics import silhouette_score
from sklearn.cluster import estimate_bandwidth
import matplotlib.pyplot as plt
from google.colab import files
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, silhouette_score
from sklearn.decomposition import PCA

# Data Loading
uploaded = files.upload()
df = pd.read_csv("credit_score_dataset.csv")

# Data Preprocessing Function
def preprocess_function(df):
    df = df.drop(columns=["ID_Number"])

    le_education = LabelEncoder()
    le_residence = LabelEncoder()
    df["Education_Level"] = le_education.fit_transform(df["Education_Level"])
    df["Place_of_Residence"] = le_residence.fit_transform(df["Place_of_Residence"])

    scaler = MinMaxScaler()
    df[["Years_of_Experience", "Number_of_Kids"]] = scaler.fit_transform(df[["Years_of_Experience", "Number_of_Kids"]])

# Missing Data Check
    if df.isnull().sum().sum() > 0:
        print("Eksik veri bulundu. Ortalamalar ile doldurulacak...")
        df = df.fillna(df.mean())

    # Save Processed Data
    preprocessed_file_path = "preprocessed_data.csv"
    df.to_csv(preprocessed_file_path, index=False)
    print(f"Preprocessed data saved to: {preprocessed_file_path}")
    return preprocessed_file_path

preprocessed_file_path = preprocess_function(df)
print("Kaydedilen dosya yolu:", preprocessed_file_path)

import os
print(os.listdir())  # List All Files in the Working Directory

from google.colab import files

# Download the Preprocessed Data File
files.download("preprocessed_data.csv")

def optimal_k(X):
    best_k = 2
    best_score = -1
    for k in range(2, 11):
        model = KMeans(n_clusters=k, random_state=42)
        labels = model.fit_predict(X)
        score = silhouette_score(X, labels)
        if score > best_score:
            best_k = k
            best_score = score
    print(f"Optimal K: {best_k} - Silhouette Skoru: {best_score:.4f}")
    return best_k

# DBSCAN Parameter Tuning Function
def tune_dbscan_advanced(X):
    best_eps = 0.5
    best_min_samples = 5
    best_score = -1

    for eps in np.arange(0.05, 2.5, 0.01):
        for min_samples in range(2, 30):
            model = DBSCAN(eps=eps, min_samples=min_samples)
            labels = model.fit_predict(X)
            if len(set(labels)) > 1:
                score = silhouette_score(X, labels)
                if score > best_score:
                    best_eps = eps
                    best_min_samples = min_samples
                    best_score = score

    print(f"DBSCAN En İyi Parametreler: eps={best_eps}, min_samples={best_min_samples}, Skor: {best_score:.4f}")
    return best_eps, best_min_samples

def tune_meanshift_advanced(X):
    best_bandwidth = estimate_bandwidth(X, quantile=0.1, n_samples=len(X))
    print(f"Mean Shift En İyi Bant Genişliği: {best_bandwidth:.4f}")
    return best_bandwidth

# Model Training Function
def train_model(X, model_type="kmeans", **kwargs):
    if model_type == "kmeans":
        n_clusters = kwargs.get("n_clusters", 5)
        model = KMeans(n_clusters=n_clusters, random_state=42)
        model.fit(X)
        labels = model.labels_
        score = silhouette_score(X, labels)
        print(f"K-Means Modeli Eğitildi. Silhouette Skoru: {score:.4f}")

    elif model_type == "dbscan":
        eps = kwargs.get("eps", 0.5)
        min_samples = kwargs.get("min_samples", 5)
        model = DBSCAN(eps=eps, min_samples=min_samples)
        model.fit(X)
        labels = model.labels_
        if len(set(labels)) > 1:  # En az 2 küme varsa skor hesaplanır
            score = silhouette_score(X, labels)
            print(f"DBSCAN Modeli Eğitildi. Silhouette Skoru: {score:.4f}")
        else:
            score = -1  # Silhouette skoru hesaplanamaz
            print("DBSCAN sonucu tek bir küme içeriyor. Silhouette Skoru hesaplanamadı.")

    elif model_type == "meanshift":
        bandwidth = kwargs.get("bandwidth", None)
        model = MeanShift(bandwidth=bandwidth)
        model.fit(X)
        labels = model.labels_
        score = silhouette_score(X, labels)
        print(f"Mean Shift Modeli Eğitildi. Silhouette Skoru: {score:.4f}")

    else:
        raise ValueError("Geçersiz model türü. 'kmeans', 'dbscan' veya 'meanshift' seçmelisiniz.")

    return labels, score

# Main Program
if __name__ == "__main__":
    preprocessed_file_path = preprocess_function(df)
    df_preprocessed = pd.read_csv(preprocessed_file_path)
    X = df_preprocessed.drop(columns=["Is_Married", "Is_House_Rent", "Has_Car"])

    # K-Means Clustering
    labels_kmeans, score_kmeans = train_model(X, model_type="kmeans")

    # DBSCAN Clustering
    best_eps, best_min_samples = tune_dbscan(X)
    labels_dbscan, score_dbscan = train_model(X, model_type="dbscan", eps=best_eps, min_samples=best_min_samples)

    # Mean Shift Best Bandwidth Tuning
    best_bandwidth = tune_meanshift(X)
    labels_meanshift, score_meanshift = train_model(X, model_type="meanshift", bandwidth=best_bandwidth)

    # Clustering Visualization
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=labels_kmeans, cmap="viridis", s=50)
    plt.title(f"K-Means Clustering\nSilhouette: {score_kmeans:.2f}")

    plt.subplot(1, 3, 2)
    plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=labels_dbscan, cmap="viridis", s=50)
    plt.title(f"DBSCAN Clustering\nSilhouette: {score_dbscan:.2f}")

    plt.subplot(1, 3, 3)
    plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=labels_meanshift, cmap="viridis", s=50)
    plt.title(f"Mean Shift Clustering\nSilhouette: {score_meanshift:.2f}")

    plt.show()