# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1N7MEWGU03O6GFX2Bg42X4sq55awmE_
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()
uploaded = files.upload()

# Load the preprocessed data
train_data = pd.read_csv("processed_train.csv")
test_data = pd.read_csv("processed_test.csv")

# Features and target
features = ['Height_converted', 'Weight']
target = 'normal_weight'
X_train = train_data[features]
y_train = train_data[target]
X_test = test_data[features]
y_test = test_data[target]


best_k = 9

# Weighted KNN Model (weights='distance')
knn_weighted = KNeighborsClassifier(n_neighbors=best_k, weights='distance')
knn_weighted.fit(X_train, y_train)
knn_weighted_pred = knn_weighted.predict(X_test)

# Accuracy and classification report
print(f"Weighted KNN Accuracy with n_neighbors={best_k}: {accuracy_score(y_test, knn_weighted_pred)}")
print(f"Weighted KNN Classification Report with n_neighbors={best_k}:\n", classification_report(y_test, knn_weighted_pred))

# ANN
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1500, random_state=42)
mlp.fit(X_train, y_train)
mlp_pred = mlp.predict(X_test)
print("ANN Accuracy:", accuracy_score(y_test, mlp_pred))
print("ANN Classification Report:\n", classification_report(y_test, mlp_pred))


# Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("Random Forest Classification Report:\n", classification_report(y_test, rf_pred))


# Model Comparison
model_names = [ 'KNN', 'ANN', 'Random Forest']
accuracies = [

    accuracy_score(y_test, knn_pred),
    accuracy_score(y_test, mlp_pred),
    accuracy_score(y_test, rf_pred)
]

plt.figure(figsize=(10, 5))
plt.bar(model_names, accuracies, color=[ 'green', 'orange', 'red'])
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.title('Model Comparison')
plt.show()