# -*- coding: utf-8 -*-
"""preprocessing_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-Rd3iAAlSkBIsyuaSMrCMxxq2GKGb7Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from google.colab import files
uploaded = files.upload()

# Data loading
df = pd.read_csv("CTIS471_2425_first_part.csv")

# Convertings
def convert_height_to_inches(row):
    if row['metric'] == 'EU':
        return row['Height'] * 39.3701
    elif row['metric'] == 'USA':
        return row['Height']
    else:
        return None
df['Height_converted'] = df.apply(convert_height_to_inches, axis=1)

df['Height_converted'] = df.apply(convert_height_to_inches, axis=1)
print(df[['Height', 'metric', 'Height_converted']].head())

# explanatory data analysis (EDA)
print("Data Info:")
print(df.info())
print("\nNumber of Missing Data:")
print(df.isnull().sum())
print(df.head())

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['Height_converted'], kde=True, color='skyblue')
plt.title("Height Distribution")

plt.subplot(1, 2, 2)
sns.histplot(df['Weight'], kde=True, color='lightgreen')
plt.title("Weight Distribution")
plt.show()

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.boxplot(y=df['Height_converted'], color='skyblue')
plt.title("Height Boxplot")

plt.subplot(1, 2, 2)
sns.boxplot(y=df['Weight'], color='lightgreen')
plt.title("Weight Boxplot")
plt.show()

# Filtering outliers
Q1 = df['Height_converted'].quantile(0.25)
Q3 = df['Height_converted'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df['Height_converted'] >= lower_bound) & (df['Height_converted'] <= upper_bound)]

# Feature and target variable
features = ['Height_converted', 'Weight']
target = 'normal_weight'

# Train-test split
X = df[features]
y = df[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling with pipeline
preprocessing_pipeline = Pipeline(steps=[('scaler', StandardScaler())])
X_train_scaled = preprocessing_pipeline.fit_transform(X_train)
X_test_scaled = preprocessing_pipeline.transform(X_test)

# Saving the processed data
X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_train_scaled_df[target] = y_train.values
X_train_scaled_df.to_csv("processed_train.csv", index=False)

X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=X_test.columns)
X_test_scaled_df[target] = y_test.values
X_test_scaled_df.to_csv("processed_test.csv", index=False)

files.download("processed_train.csv")
files.download("processed_test.csv")